-- =============================================
-- MIGRAÇÃO v2.2 - Correção do Cálculo de Ritmo + Persistência
-- Data: 2026-02-09
-- =============================================
-- Esta migração NÃO faz alterações no banco de dados.
-- As correções são apenas no código TypeScript.
-- 
-- CORREÇÕES IMPLEMENTADAS:
-- =============================================
-- 
-- 1. CÁLCULO BASEADO NO INTERVALO REAL DE TEMPO
--    - Antes: calculava páginas/dia dividindo por dias únicos de leitura
--    - Agora: calcula dividindo páginas lidas pelo intervalo total
--      (dias entre primeira e última leitura)
-- 
-- 2. BARRA DE PROGRESSO VISUAL (Progress Component)
--    - Componente Progress melhorado com indicatorClassName
--    - Suporta customização de cores do indicador
--    - Animação suave de transição
-- 
-- 3. PERSISTÊNCIA DE ESTADO EM DISPOSITIVOS MÓVEIS
--    - Salva view atual no sessionStorage
--    - Salva posição de scroll ao minimizar/fechar
--    - Restaura estado ao retornar à página
--    - Usa visibilitychange API para detectar background
-- 
-- ARQUIVOS MODIFICADOS:
-- =============================================
-- - src/lib/readingProjections.ts
--   - Encontra firstReadingDate e lastReadingDate
--   - Calcula totalDaysElapsed = diferença entre datas + 1
--   - avgPagesPerDay = quantidadeLida / totalDaysElapsed
-- 
-- - src/components/ui/progress.tsx
--   - Adicionada prop indicatorClassName
--   - Melhorada animação com duration-300
-- 
-- - src/pages/Index.tsx
--   - Estado inicial lido do sessionStorage
--   - useEffect para persistir currentView e booksFilter
--   - Listeners para visibilitychange e beforeunload
--   - Restaura scroll position no mount
-- 
-- =============================================
